version: '2'
services:
  jenkins:
    build: ./jenkins-master/
    image: jenkins-local-master
    networks:
      - jenkins
    ports:
      - '8080:8080'
    volumes:
      - 'jenkins_data:/var/jenkins_home'
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins-slave:
    build: ./jenkins-slave/
    image: jenkins-local-slave
    networks:
      - jenkins
  git-server:
    build: ./git-server/
    image: git-local-server
    volumes:
      - ./git-server/seed-repos/:/git/seed-repos/
    networks:
      - jenkins
    ports:
      - '9418:9418'
networks:
  jenkins:
volumes:
  jenkins_data:
    driver: local
